language: generic
compiler: gcc
matrix:
  include:
    - name: 'ROS Indigo'
      dist: trusty
      env: UBUNTU=trusty ROS_DISTRO=indigo
    - name: 'ROS Kinetic'
      dist: xenial
      env: UBUNTU=xenial ROS_DISTRO=kinetic

before_install:
  - echo "deb http://packages.ros.org/ros/ubuntu $UBUNTU main" | sudo tee -a /etc/apt/sources.list
  - curl http://packages.ros.org/ros.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -y dpkg ninja-build python-catkin-lint python-catkin-pkg python-catkin-tools python-rosdep

install:
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/webrtc
  - cd /tmp/ws
  - rosdep install --skip-keys ninja-build --from-paths src --ignore-src --rosdistro ${ROS_DISTRO} -y

before_script:
  - cd /tmp/ws
  - source /opt/ros/${ROS_DISTRO}/setup.bash
  - catkin config --install

script:
  - catkin_lint src/webrtc
  - catkin build -p1 --no-status -i

