dist: xenial
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - sourceline: 'deb http://packages.ros.org/ros/ubuntu xenial main'
        key_url: http://packages.ros.org/ros.key
    packages:
      - ninja-build
      - python-catkin-lint
      - python-catkin-pkg
      - python-catkin-tools
      - python-rosdep
      - ros-kinetic-catkin
install:
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/webrtc
  - cd /tmp/ws
  - rosdep install --skip-keys ninja-build --from-paths src --ignore-src --rosdistro kinetic -y

before_script:
  - cd /tmp/ws
  - source /opt/ros/kinetic/setup.bash
  - catkin config --install

script:
  - catkin_lint src/webrtc
  - catkin build -p1 --no-status -i

