language:
  - cpp
compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:libreoffice/ppa # for libicu-dev with pc files
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test # for g++4.8 (for c++11)
  - sudo add-apt-repository -y ppa:apokluda/boost1.53 # Need new boost for c++11
  - sudo apt-get update -qq
  - sudo apt-get install -qq libicu-dev # this is already installed and we need to force it to upgrade
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo apt-get install -qq libboost1.53-all-dev

  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

  # Need to satisfy apt deps
  # make libboost-all-dev marked as installed
  - sudo ln -s /usr/lib/libboost_signals.so /usr/lib/libboost_signals-mt.so
  - sudo ln -s /usr/lib/libboost_filesystem.so /usr/lib/libboost_filesystem-mt.so
  - sudo ln -s /usr/lib/libboost_regex.so /usr/lib/libboost_regex-mt.so
  - sudo ln -s /usr/lib/libboost_system.so /usr/lib/libboost_system-mt.so
  - sudo ln -s /usr/lib/libboost_date_time.so /usr/lib/libboost_date_time-mt.so
  - sudo ln -s /usr/lib/libboost_thread.so /usr/lib/libboost_thread-mt.so
  - sudo apt-get install -qq equivs
  - equivs-build .travis-boost-config
  - sudo dpkg -i libboost-all-dev_42_all.deb

  # Need cmake 2.8.12
  - pushd /tmp
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2.tar.gz
  - tar -xzf cmake-2.8.12.2.tar.gz
  - cd cmake-2.8.12.2
  - ./bootstrap
  - make
  - sudo make install
  - popd

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-catkin-pkg python-rosdep ros-hydro-catkin python-catkin-tools -qq
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/package
  - cd /tmp/ws/src
  - git clone https://github.com/WPI-RAIL/async_web_server_cpp.git
  - cd /tmp/ws
  - rosdep install --from-paths src --ignore-src --rosdistro hydro -y

script:
  - cd /tmp/ws
  - source /opt/ros/hydro/setup.bash
  - catkin init
  - catkin config --install
  - catkin build -p1 -j4 --no-status
  - source install/setup.bash
